### ISSUE TITLE
firefox配置页面缺失

### ISSUE THREAD

**Issue by qingfua** [Justineo/coplay#33] opened 2020-05-01 14:31 UTC
只有chrome有options.html
ff的文件没了
![image](https://user-images.githubusercontent.com/16662647/80812911-81442380-8bfb-11ea-8c10-068647de0644.png)

**Comment by Justineo** [comment] 2020-05-01 23:58
Duplicate of #22

**Closed as completed by Justineo** 2020-05-01 23:58 UTC
